- name: Install the latest version of Apache
  package:
    name:
      - "{{ apache_package_name }}"
    state: latest
    
- name: Start and Enable service httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"